### ISSUE TITLE
http2, no data

### ISSUE THREAD

**Issue by bennn** [migeed-z/retic_performance#10]
The `http2` benchmark still doesn't have data. But it runs locally / on Karst interactively.

But it doesn't run as a batch job. I think the error is due to

```
ascii codec cannot decode ....
```

Try running 1 configuration as a batch job, maybe that will reproduce the errors.

**Comment by bennn** [comment]
mkay here's the full error:

```
Traceback (most recent call last):
  File "/N/u/zmahmoud/Karst/reticulated/retic.py", line 5, in <module>
    retic.main()
  File "/gpfs/home/z/m/zmahmoud/Karst/reticulated/retic/retic.py", line 155, in main
    reticulate(program, prog_args=args.args.split(), flag_sets=args)
  File "/gpfs/home/z/m/zmahmoud/Karst/reticulated/retic/retic.py", line 36, in reticulate
    py_ast = ast.parse(input.read())
  File "/N/u/zmahmoud/Karst/Python-3.4.3/Lib/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 619: ordinal not in range(128)
```

**Comment by bennn** [comment]
Andofcourse this runs fine from the shell and NOT FINE when submitted as a batch job. Here's a sample configuration:

[sample-http2-config.tar.gz](https://github.com/migeed-z/retic_performance/files/524976/sample-http2-config.tar.gz)

**Comment by bennn** [comment]
Converted `http2/typed/main.py` to ascii here:
6214f318ebc867165309b3904e87c49f8e0b488f

Should work now. I was at least able to run 1 configuration through `qsub` (and interactively).
