### ISSUE TITLE
Evolution error

### ISSUE THREAD

**Issue by bennn** [migeed-z/retic_performance#8]
Some Evolution configs are raising an error about:

```
import ExchangeForPopulation from exchange_for_population
```

(Sorry I didn't save the full error message from the nodes logs)

Need to reproduce & fix

**Comment by migeed-z** [comment]
okay, so in the output file, all output from line 31169 to 31862 is empty.

The benchmark in this directory: retic_performance/Evolution/test_benchmark/test1 runs and produces an output even though it is an incorrect benchmark. So we need to figure out why this benchmark works.

**Comment by migeed-z** [comment]
main is missing the return statement. So we need to add that.

**Comment by migeed-z** [comment]
actually this benchmark is fine. I copied it to my local computer and it ran, also added print statements to make sure the typed parts are being invoked, and the are. I think the benchmark is fine.

**Comment by bennn** [comment]
Just re-set the inputs for Evolution (and filtered out the configs that have already run).
Here are the inputs -- these are also "live" on the cluster in the `retic_performance/Evolution` folder.
[input.tar.gz](https://github.com/migeed-z/retic_performance/files/525715/input.tar.gz)

And here is the output for Evolution so far:
[orig-karst_output.tar.gz](https://github.com/migeed-z/retic_performance/files/525662/orig-karst_output.tar.gz)

**Comment by bennn** [comment]
Here's the full error we were getting before:

```
Traceback (most recent call last):
  File "/tmp/1798897.m2/reticulated/retic.py", line 5, in <module>
    retic.main()
  File "/tmp/1798897.m2/reticulated/retic/retic.py", line 155, in main
    reticulate(program, prog_args=args.args.split(), flag_sets=args)
  File "/tmp/1798897.m2/reticulated/retic/retic.py", line 104, in reticulate
    utils.handle_runtime_error(exit=True)
  File "/tmp/1798897.m2/reticulated/retic/retic.py", line 102, in reticulate
    _exec(code, __main__.__dict__)
  File "/tmp/1798897.m2/reticulated/retic/exec3/__init__.py", line 2, in _exec
    exec (obj, globs, locs)
  File "/N/u/zmahmoud/Karst/retic_performance/Evolution//Test/1798897.m2/main.py", line 258, in <module>
  File "/tmp/1798897.m2/reticulated/retic/importer.py", line 113, in exec_module
    _exec(code, module.__dict__)
  File "/tmp/1798897.m2/reticulated/retic/exec3/__init__.py", line 2, in _exec
    exec (obj, globs, locs)
  File "/N/u/zmahmoud/Karst/retic_performance/Evolution/Test/1798897.m2/evolution/player/player.py", line 12, in <module>
    from exchange_for_species import ExchangeForSpecies
ImportError: No module named 'exchange_for_species'
```

Maybe, because there was a bad configuration number & that version of `exchange_for_species.py` didn't exist.
